# Splunk Universal Forwarder - inputs.conf
# Location: C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf
# Windows 10 VM (Target Machine)

[WinEventLog://Security]
index = main
disabled = 0

[WinEventLog://System]
index = main
disabled = 0

[WinEventLog://Application]
index = main
disabled = 0

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = main
disabled = 0

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
index = main
disabled = 0
